const {chromium}=require('playwright');
const fs=require('fs'),http=require('http'),assert=require('assert');const path=require('path'),os=require('os');let root=path.resolve(__dirname,'..');
const server=http.createServer((q,r)=>{let p=decodeURIComponent(new URL(q.url,'http://localhost').pathname);if(p==='/')p='/index.html';try{r.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');r.end(fs.readFileSync(root+p))}catch{r.statusCode=404;r.end()}});
const profile=fs.mkdtempSync(require('path').join(require('os').tmpdir(),'conectalsch-test-'));
async function mocks(context){
await context.route('https://cdn.jsdelivr.net/**',route=>route.fulfill({contentType:'text/javascript',body:`
export const FilesetResolver={forVisionTasks:async()=>({})};
const hand=d=>Array.from({length:21},(_,i)=>({x:.3+d*i/60,y:.25+i/80,z:0}));
export const HandLandmarker={createFromOptions:async()=>{window.handCreates++;return {detectForVideo(){window.inferences++;const start=performance.now();while(performance.now()-start<window.inferenceDelay){};return {landmarks:window.mode==='none'?[]:window.mode==='two'?[hand(1),hand(-1)]:window.mode==='unknown'?[hand(1).map((p,i)=>({x:.4+Math.sin(i)*.2,y:.5+Math.cos(i)*.2,z:Math.sin(i/3)}))]:[hand(window.mode==='family'?-1:1)]}}}}};
export const FaceLandmarker={createFromOptions:async()=>{window.faceCreates++;return {close(){},detectForVideo(){window.faceCalls++;return {faceLandmarks:window.faceVisible?[Array.from({length:478},(_,i)=>({x:.4+i/5000,y:.2+i/6000,z:0}))]:[],faceBlendshapes:[{categories:[{categoryName:'browInnerUp',score:window.brow},{categoryName:'mouthSmileLeft',score:.9}]}]}}}}};
export const PoseLandmarker={createFromOptions:async()=>{window.poseCreates++;return {close(){},detectForVideo(){window.poseCalls++;return {landmarks:[Array.from({length:33},(_,i)=>({x:.3+i/100,y:.5+i/100,z:0,visibility:window.bodyVisible?.9:.1}))]}}}}};
`}));
await context.addInitScript(()=>{
window.mode='none';window.spoken=[];window.copied='';window.stops=0;window.inferences=0;window.inferenceDelay=0;window.handCreates=0;window.faceCreates=0;window.poseCreates=0;window.faceCalls=0;window.poseCalls=0;window.faceVisible=true;window.bodyVisible=true;window.brow=.1;window.testWidth=640;window.testHeight=480;
Object.defineProperty(window,'speechSynthesis',{value:{cancel(){},speak(u){spoken.push(u.text)}}});window.SpeechSynthesisUtterance=class{constructor(text){this.text=text}};
Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{copied=text}}});window.SpeechRecognition=class{constructor(){window.testRec=this}start(){this.onstart?.()}stop(){this.onend?.()}};
navigator.mediaDevices.getUserMedia=async()=>({getTracks:()=>[{stop(){stops++}}]});
Object.defineProperty(HTMLMediaElement.prototype,'srcObject',{set(){},get(){return null}});HTMLMediaElement.prototype.play=async()=>{};
Object.defineProperty(HTMLMediaElement.prototype,'readyState',{get:()=>4});Object.defineProperty(HTMLMediaElement.prototype,'currentTime',{get:()=>performance.now()/1000});Object.defineProperty(HTMLVideoElement.prototype,'videoWidth',{get:()=>testWidth});Object.defineProperty(HTMLVideoElement.prototype,'videoHeight',{get:()=>testHeight});
// Deliberately leave a retired base cache. v1.2.1 must never use it as recognition data.
if(!localStorage.getItem('conectalsch-v10-templates'))localStorage.setItem('conectalsch-v10-templates',JSON.stringify(['HOLA','GRACIAS','SÍ','NO','AYÚDAME'].map(label=>({label,seq:Array.from({length:9},()=>Array(126).fill(0))}))));
});
}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const launch=()=>chromium.launchPersistentContext(profile,{...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{}),headless:true,viewport:{width:390,height:844},serviceWorkers:'block'});let context=await launch();try{await mocks(context);let page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>document.querySelector('#signResult').textContent.includes('Aún no tienes'));assert.equal(await page.locator('#signDictionary li').count(),0);assert(await page.locator('#startRecognition').isDisabled());const oldCache=await page.evaluate(()=>localStorage.getItem('conectalsch-v10-templates'));assert.equal(await page.evaluate(()=>handCreates),0);console.log('PASS empty personal library ignores all retired originals and loads no vision model');
async function capture(label,mode){await page.click('#tab-samples');if(!await page.locator('#trainingDetails').evaluate(e=>e.open))await page.locator('#trainingDetails summary').click();await page.fill('#signName',label);await page.evaluate(mode=>window.mode=mode,mode);await page.click('#recordSample');try{await page.waitForFunction(label=>document.querySelector('#trainingStatus').textContent.includes('Ejemplo de '+label+' guardado'),label,{timeout:16000})}catch(e){console.log(await page.evaluate(()=>({training:document.querySelector('#trainingStatus').textContent,confidence:document.querySelector('#confidence').textContent,inferences,handCreates,invalidSample:window.invalidSample})),errors);throw e}}
await capture('HOLA','hola');await capture('HOLA','hola');await capture('FAMILIA','family');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('conectalsch-personal-v1')));assert.equal(saved.length,3);assert(saved.every(s=>s.sampleVersion===2&&s.seq.length>9&&s.landmarks.length===s.seq.length&&s.timestamps.length===s.seq.length));assert(saved.filter(s=>s.label==='HOLA').length===2);console.log('PASS camera capture: HOLA x2 + second sign, full frames/timing/landmarks retained');
await page.evaluate(()=>mode='none');await page.click('#startRecognition');await page.waitForTimeout(1000);assert.equal(await page.locator('#signResult').innerText(),'No se detectan manos');assert.equal(await page.evaluate(()=>spoken.length),0);await page.evaluate(()=>mode='hola');await page.waitForFunction(()=>spoken.length===1,{},{timeout:12000});assert.equal(await page.locator('#signResult').innerText(),'HOLA');await page.waitForTimeout(2300);assert.equal(await page.evaluate(()=>spoken.length),1);await page.evaluate(()=>mode='none');await page.waitForTimeout(900);await page.evaluate(()=>mode='family');await page.waitForFunction(()=>spoken.length===2,{},{timeout:12000});assert.equal(await page.locator('#signResult').innerText(),'FAMILIA');await page.evaluate(()=>mode='none');await page.waitForTimeout(900);await page.evaluate(()=>mode='unknown');await page.waitForFunction(()=>document.querySelector('#signResult').textContent==='No estoy seguro',{},{timeout:12000});assert.equal(await page.evaluate(()=>spoken.length),2);console.log('PASS trained HOLA/family distinguished; no hands/unknown silent; held sign speaks once; withdrawal rearms');
await page.getByText('Estado del reconocimiento',{exact:true}).click();await page.click('#toggleDiagnostics');assert.match(await page.locator('#diagnosticValues').innerText(),/DTW.*Segundo.*Diferencia/s);await page.click('#toggleOverlay');await page.evaluate(()=>mode='two');await page.waitForFunction(()=>document.querySelector('#handsStatus').textContent.includes('2'));assert(await page.evaluate(()=>document.querySelector('#handCanvas').getContext('2d').getImageData(0,0,testWidth,testHeight).data.some(x=>x)));await page.click('#flipCamera');await page.waitForFunction(()=>document.querySelector('#handsStatus').textContent.includes('2'));assert(await page.evaluate(()=>getComputedStyle(document.querySelector('#camera')).transform==='none'&&getComputedStyle(document.querySelector('#handCanvas')).transform==='none'));await page.evaluate(()=>{testWidth=480;testHeight=640;document.querySelector('#camera').dispatchEvent(new Event('resize'))});await page.waitForTimeout(300);assert(await page.evaluate(()=>{const v=document.querySelector('#camera').getBoundingClientRect(),c=document.querySelector('#handCanvas').getBoundingClientRect();return Math.abs(v.width/v.height-.75)<.01&&v.width===c.width&&v.height===c.height&&document.querySelector('#handCanvas').width===480}));console.log('PASS two hands, camera flip and portrait aspect keep overlay aligned');
await page.click('#toggleVisual');await page.waitForFunction(()=>faceCalls>0&&poseCalls>0);const visualBefore=await page.evaluate(()=>({face:faceCalls,pose:poseCalls}));await page.waitForTimeout(1100);assert(await page.evaluate(v=>faceCalls-v.face<=4&&poseCalls-v.pose<=4,visualBefore));await page.evaluate(()=>{faceVisible=false;bodyVisible=false;brow=.9});await page.waitForTimeout(800);assert.match(await page.locator('#visualStatus').innerText(),/no disponible/);assert.equal(await page.evaluate(()=>spoken.length),2);await page.click('#toggleOverlay');assert(!await page.evaluate(()=>document.querySelector('#handCanvas').getContext('2d').getImageData(0,0,testWidth,testHeight).data.some(x=>x)));const calls=await page.evaluate(()=>faceCalls+poseCalls);await page.waitForTimeout(700);assert.equal(await page.evaluate(()=>faceCalls+poseCalls),calls);await page.click('#toggleVisual');console.log('PASS optional face/pose cadence, unavailable channels, overlay OFF; no voice dependency');
for(let i=0;i<3;i++){await page.click('#tab-notes');const n=await page.evaluate(()=>inferences);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>inferences),n);await page.click('#tab-signs');await page.click('#toggleCamera');await page.waitForFunction(()=>document.querySelector('#handsStatus').textContent.includes('2'))}assert.equal(await page.evaluate(()=>handCreates),1);console.log('PASS one reusable hand model; tab changes stop camera processing');
await page.click('#tab-listen');await page.click('#toggleListening');await page.evaluate(()=>{for(const text of ['Primera frase.','Segunda frase.']){const r=[{transcript:text}];r.isFinal=true;testRec.onresult({resultIndex:0,results:[r]})}});await page.click('#copySubtitles');assert.equal(await page.evaluate(()=>copied),'Primera frase.\nSegunda frase.');await page.click('#saveNote');await page.waitForFunction(()=>document.querySelector('#noteStatus').textContent.includes('Nota guardada'));await page.reload();await page.click('#tab-listen');assert.match(await page.locator('#subtitleHistory').innerText(),/Segunda/);await page.click('#clearSubtitles');await page.click('#tab-notes');await page.locator('.note-item').click();assert.match(await page.locator('#noteText').innerText(),/Primera.*Segunda/s);assert(await page.locator('#noteDate').innerText());console.log('PASS speech->subtitles->save note; draft survives refresh; clear does not delete notes');
await page.click('#tab-samples');const pending=page.waitForEvent('download');await page.click('#exportSamples');const backup=JSON.parse(fs.readFileSync(await (await pending).path(),'utf8'));assert.equal(backup.version,2);assert.equal(backup.schemaVersion,2);assert.deepEqual(backup.samples,saved);await page.setInputFiles('#samplesFile',{name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>document.querySelector('#trainingStatus').textContent.includes('0 ejemplos nuevos'));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('conectalsch-personal-v1')).length),3);
const legacy={format:'conectalsch-personal',version:1,samples:[{label:'LEGADO',seq:Array.from({length:9},()=>Array(126).fill(0))}]};await page.setInputFiles('#samplesFile',{name:'old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await page.waitForFunction(()=>document.querySelector('#signDictionary').textContent.includes('LEGADO'));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('conectalsch-personal-v1')).length),4);assert.equal(await page.evaluate(()=>localStorage.getItem('conectalsch-v10-templates')),oldCache);console.log('PASS JSON v2 round-trip/dedup + v1 import merges, no old caches or existing data erased');
assert.deepEqual(errors,[]);await context.close();context=await launch();await mocks(context);page=await context.newPage();await page.goto(url);await page.waitForFunction(()=>document.querySelector('#signDictionary').textContent.includes('HOLA'));await page.click('#tab-notes');await page.locator('.note-item').click();assert.match(await page.locator('#noteText').innerText(),/Segunda/);await page.click('#tab-samples');await page.locator('#manageDetails summary').click();await page.selectOption('#manageSign','HOLA');page.once('dialog',d=>d.dismiss());await page.click('#deleteSign');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('conectalsch-personal-v1')).length),4);page.once('dialog',d=>d.accept());await page.click('#deleteSign');await page.waitForFunction(()=>!document.querySelector('#signDictionary').textContent.includes('HOLA'));await page.reload();await page.waitForFunction(()=>document.querySelector('#signDictionary').textContent.includes('FAMILIA'));assert(!await page.locator('#signDictionary').innerText().then(t=>t.includes('HOLA')));console.log('PASS full browser close/reopen retains samples/notes; confirmed deletion updates both mirrors');
for(const [width,height] of [[320,568],[390,844],[844,390],[768,1024],[1440,900]]){await page.setViewportSize({width,height});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const nav=await page.locator('.main-nav').boundingBox();assert(nav.y+nav.height<=height+1)}console.log('PASS five responsive sizes and fixed bottom tabs');
}finally{await context.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});


