// Separate from conectalsch-personal / samples; existing sample storage is untouched.
const DB='conectalsch-content';
function open(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{for(const name of ['notes','settings'])if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Cierra otras pestañas de la aplicación e inténtalo de nuevo.'))})}
async function operation(store,mode,action){const db=await open();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(store,mode),r=action(tx.objectStore(store));tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Operación cancelada'))})}finally{db.close()}}
export async function saveNote(text,segments=[]){text=text.trim();if(!text)throw Error('No hay subtítulos confirmados para guardar.');const createdAt=new Date().toISOString();const note={id:crypto.randomUUID(),schemaVersion:1,kind:'transcript',text,title:text.split('\n')[0].slice(0,80),createdAt,updatedAt:createdAt,language:'es-CL',segments:structuredClone(segments),attachments:[]};await operation('notes','readwrite',s=>s.add(note));return note}
export async function listNotes(){return (await operation('notes','readonly',s=>s.getAll())).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
export async function deleteNote(id){await operation('notes','readwrite',s=>s.delete(id))}
export async function getSignSettings(){return (await operation('settings','readonly',s=>s.get('sign-settings')))?.values||{}}
export async function putSignSettings(values){await operation('settings','readwrite',s=>s.put({id:'sign-settings',schemaVersion:1,values}))}
export async function copyText(text,element){if(!text.trim())throw Error('No hay texto para copiar.');try{await navigator.clipboard.writeText(text);return 'Texto copiado.'}catch{if(element){const selection=getSelection(),range=document.createRange();range.selectNodeContents(element);selection.removeAllRanges();selection.addRange(range)}return 'Selecciona el texto y usa Copiar en el menú del navegador.'}}
